# Pauli Matrices

The Pauli spin matrices are defined as follows:

In [1]:
import numpy as np


X = np.array([
                [0, 1], 
                [1, 0]
])

Y = np.array([
                [0, -1j], 
                [1j, 0]
])

Z = np.array([
                [1, 0], 
                [0, -1]
])

print ('X:')
print(X)

print ('Y:')
print(Y)

print ('Z:')
print(Z)

X:
[[0 1]
 [1 0]]
Y:
[[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]
Z:
[[ 1  0]
 [ 0 -1]]


In physical contexts, the each Pauli matrix is multiplied by $\hbar /2.$ See here for how the Pauli matrices can be used to model the spin of an electron: https://chemphys.uconn.edu/~ch351vc/pdfs/spin1.pdf

The Pauli matrices are a basis for the vector space of 2 x 2 Hermitian matrices with complex entries. The Pauli matrices together with the identity matrix are a basis for the vector space of 2 x 2 matrices. complex entries. That is, any 2 x 2 matrix can be expressed as a linear combination of these four matrices.

Because all single-qubit quantum gates can be represented by 2 × 2 unitary matrices, any single qubit quantum gate can be expressed as a linear combination of Pauli matrices.

The Pauli matrices satisfy the following properties:

1. Each Pauli matrix is unitary.
2. Each Pauli matrix is Hermitian.
3. The square of any Pauli matrix is the identity matrix. A matrix which is its own inverse is called *involutory*.
4. The determinant of each Pauli matrix is -1.
5. The trace of each Pauli matrix is 0.
6. If we multiply any two distinct Pauli matrices, we get the negative of the third Pauli matrix.

We can see that these properties hold as follows:

In [2]:
import numpy.linalg as la

def dagger(matrix):
    return np.transpose(np.conjugate(matrix))

def project(matrix):
    return matrix @ dagger(matrix)

# pauli matrices are often collected into one vector
S = [X, Y, Z]

print('each Pauli matrix is unitary:')
for i in range(3):
    print(np.array_equal(project(S[i]), np.eye(2)))

print('each Pauli matrix is hermitian:')
for i in range(3):
    print(np.array_equal(S[i], dagger(S[i])))

print('each Pauli matrix is involutory:')
for i in range(3):
    print(np.array_equal(S[i] @ S[i], np.eye(2)))
    
print('each Pauli matrix has a determinant of -1:')
for i in range(3):
    print(la.det(S[i]))
    
print('each Pauli matrix has a trace of 0:')
for i in range(3):
    print(np.trace(S[i]))
    
print('multiplication of two distinct Pauli matirces yields the negative of the third:')
print((S[0] @ S[1]))
print(S[2])

each Pauli matrix is unitary:
True
True
True
each Pauli matrix is hermitian:
True
True
True
each Pauli matrix is involutory:
True
True
True
each Pauli matrix has a determinant of -1:
-1.0
(-1+0j)
-1.0
each Pauli matrix has a trace of 0:
0
0j
0
multiplication of two distinct Pauli matirces yields the negative of the third:
[[0.+1.j 0.+0.j]
 [0.+0.j 0.-1.j]]
[[ 1  0]
 [ 0 -1]]


The value of the Levi-Civita symbol is 1 if (i, j, k) is an *even permutation* of (0, 1, 2), −1 for *odd permutations* and 0 for all other cases.

In particular, the three-dimensional *Levi-Civita symbol* is a function *f* taking triples of numbers (i,j,k) each in {0, 1, 2}, to {-1,0,1}, defined as:

f(i,j,k) = 0 when i,j,k are not distinct, i.e. i=j or j=k or k=i
f(i,j,k) = 1 when (i,j,k) is a cyclic shift of (0, 1, 2), that is one of (0, 1, 2), (1, 2, 0), (2 ,0, 1).
f(i,j,k) = -1 when (i,j,k) is a cyclic shift of (2 ,1, 0), that is one of (2, 1, 0), (1, 0, 2), (0, 2, 1).

We can implement the Levi-Civita symbol as follows:

In [3]:
def levi_civita(three_tuple):
    if (three_tuple[0] == three_tuple[1] or 
        three_tuple[1] == three_tuple[2] 
        or three_tuple[0] == three_tuple[2]):
        return 0
    if three_tuple == (0, 1, 2) or three_tuple == (1, 2, 0) or three_tuple == (2, 0, 1):
        return 1
    return -1

print(levi_civita((0, 0, 3)))
print(levi_civita((0, 1, 1)))
print(levi_civita((2, 1, 2)))

print(levi_civita((0, 1, 2)))
print(levi_civita((1, 2, 0)))
print(levi_civita((2, 0, 1)))

print(levi_civita((2, 1, 0)))
print(levi_civita((1, 0, 2)))
print(levi_civita((0, 2, 1)))


0
0
0
1
1
1
-1
-1
-1


In [4]:
print('commutation relation 1:')
print(S[0] @ S[1] - S[1] @ S[0])
print(2j * levi_civita((0, 1, 2)) * S[2])

print('commutation relation 2:')
print(S[1] @ S[0] - S[0] @ S[1])
print(2j * levi_civita((1, 0, 2)) * S[2])

print('commutation relation 3:')
print(S[1] @ S[2] - S[2] @ S[1])
print(2j * levi_civita((1, 2, 0)) * S[0])

print('commutation relation 4:')
print(S[2] @ S[1] - S[1] @ S[2])
print(2j * levi_civita((2, 1, 0)) * S[0])

print('commutation relation 5:')
print(S[0] @ S[2] - S[2] @ S[0])
print(2j * levi_civita((0, 2, 1)) * S[1])

print('commutation relation 6:')
print(S[2] @ S[0] - S[0] @ S[2])
print(2j * levi_civita((2, 0, 1)) * S[1])

commutation relation 1:
[[0.+2.j 0.+0.j]
 [0.+0.j 0.-2.j]]
[[ 0.+2.j  0.+0.j]
 [ 0.+0.j -0.-2.j]]
commutation relation 2:
[[0.-2.j 0.+0.j]
 [0.+0.j 0.+2.j]]
[[0.-2.j 0.-0.j]
 [0.-0.j 0.+2.j]]
commutation relation 3:
[[0.+0.j 0.+2.j]
 [0.+2.j 0.+0.j]]
[[0.+0.j 0.+2.j]
 [0.+2.j 0.+0.j]]
commutation relation 4:
[[0.+0.j 0.-2.j]
 [0.-2.j 0.+0.j]]
[[0.-0.j 0.-2.j]
 [0.-2.j 0.-0.j]]
commutation relation 5:
[[ 0 -2]
 [ 2  0]]
[[ 0.-0.j -2.+0.j]
 [ 2.-0.j  0.-0.j]]
commutation relation 6:
[[ 0  2]
 [-2  0]]
[[ 0.+0.j  2.-0.j]
 [-2.+0.j  0.+0.j]]


The following argument shows that any 2 x 2 matrix can be expressed as a linear combination of the three Pauli matrices together with the identity matrix:

$A = \begin{bmatrix}a & b\\c & d\end{bmatrix}$

$= \lambda_0 I +\lambda_x X +\lambda_y Y +\lambda_z Z$ 

$= \begin{bmatrix}\lambda_0 + \lambda_z & \lambda_x - i\lambda_y\\\lambda_x + i\lambda_y & \lambda_0 -  \lambda_z \end{bmatrix}$ 

which yields:

$a = \lambda_0 + \lambda_z,$

$b = \lambda_x - i\lambda_y,$

$c = \lambda_x + i\lambda_y,$

$d = \lambda_0 -  \lambda_z.$

Solving these equations leads to the following:

$\lambda_0 = \frac{a + d}{2},$

$\lambda_x = \frac{b + c}{2},$

$\lambda_y = \frac{c - b}{2i},$

$\lambda_z = \frac{a - d}{2}.$ 

We can implement a function that expresses an arbitrary matrix A as a linear combination of the above matrices as follows:

In [5]:
def pauli_decompose(A):
    '''factors a 2 x 2 matrix into a linear combination of pauli matrices.'''
    a = A[0][0]
    b = A[0][1]
    c = A[1][0]
    d = A[1][1]
    
    lambda_0 = ((a+d)/2)
    lambda_x = (b+c)/2
    lambda_y = (c-b)/2j
    lambda_z = (a-d)/2
    
    scalars = [lambda_0, lambda_x, lambda_y, lambda_z]
    return scalars

A = np.array([
              [10, 5 + 2j], 
              [3 + 4j, 15]
])

scalars = pauli_decompose(A)
linear_combination = (scalars[0] * np.eye(2)) + (scalars[1] * X) + (scalars[2] * Y) + scalars[3] * Z

print('A:')
print(A)

print('linear combination that equals A:')
print(linear_combination)

A:
[[10.+0.j  5.+2.j]
 [ 3.+4.j 15.+0.j]]
linear combination that equals A:
[[10.+0.j  5.+2.j]
 [ 3.+4.j 15.+0.j]]


The matrices $\sigma_-$ and $\sigma_+$ are defined as follows and also have interesting properties:  

In [6]:
sigma_plus = 0.5 * (X + Y*1j)
sigma_minus = 0.5 * (X - Y*1j)

print('sigma plus:')
print(sigma_plus)

print('sigma minus:')
print(sigma_minus)

anti_commutator = sigma_plus @ sigma_minus + sigma_minus @ sigma_plus

print('anti commutator is the identity:')
print(anti_commutator)

print('the squared value of each matrix is the zero matrix:')

print(sigma_plus @ sigma_plus)
print(sigma_minus @ sigma_minus)

sigma plus:
[[0.+0.j 1.+0.j]
 [0.+0.j 0.+0.j]]
sigma minus:
[[0.+0.j 0.+0.j]
 [1.+0.j 0.+0.j]]
anti commutator is the identity:
[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]
the squared value of each matrix is the zero matrix:
[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
