# Quantum Computing with Python

Quantum computing algorithms can be expressed using the standard objects of linear algebra: matrices and vectors. Classical computers cannot run quantum algorithms at scale because the associated matrices and vectors become too large (a matrix that operates on n qbits requires 2^n entries). 
Still, we can understand the concepts behind quantum computing by running small examples on classical computers.


## Matrix and Vector Operations

We can think of a *matrix* as a function that maps ordered pairs of numbers into values from some set.

For example, we can encode a 2 x 2 matrix consiting of only ones as follows:

In [1]:
from typing import Tuple

def matrix_function(indexes: Tuple[int, int]):
    if indexes == (0, 0) or indexes == (0, 1) or indexes == (1, 0) or indexes == (1 ,1):
        return 1
    
indexes = (0, 0)
print('entry (0, 0):')
matrix_function(indexes)

entry (0, 0):


1

We can also encode the same matrix as follows:

In [2]:
d = {(0, 0):1, (0, 1): 1, (1, 0): 1, (1 ,1): 1}

M = [[1, 1], [1, 1]]

print('entry (0, 0):')
print(d[(0, 0)])
print('entry (0, 0):')
print(M[0][0])

print('The whole matrix:')
print(M)

entry (0, 0):
1
entry (0, 0):
1
The whole matrix:
[[1, 1], [1, 1]]


Going forward, we will use numpy to encode our matrices as follows:

In [3]:
import numpy as np

M = np.array([[1, 1], [1, 1]])
print(M)

[[1 1]
 [1 1]]


Two matrices are equal if their corresponding components are equal. For example:

In [4]:
M = np.array([[2, 4], [6, 8]])
N = np.array([[1+1, 2+2], [3+3, 4+4]])

print('The matrices M and N are equal:')
print(np.array_equal(M, N))

The matrices M and N are equal:
True


Given two matrices, we can add them by adding their corresponding components. For example:

In [5]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print('A:')
print(A)
print('B:')
print(B)
print('A + B:')
print(A + B)

A:
[[1 2]
 [3 4]]
B:
[[5 6]
 [7 8]]
A + B:
[[ 6  8]
 [10 12]]


Given two matrices, we can multiply them as follows:

In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print('A:')
print(A)
print('B:')
print(B)
print('A x B:')
print(A @ B)

A:
[[1 2]
 [3 4]]
B:
[[5 6]
 [7 8]]
A x B:
[[19 22]
 [43 50]]


Given one matrix, we can scalar multiply that matrix as follows:

In [7]:
A = np.array([[1, 2], [3, 4]])
scalar = 5
print('A:')
print(A)
print('scalar x A:')
print(5 * A)

A:
[[1 2]
 [3 4]]
scalar x A:
[[ 5 10]
 [15 20]]


In general, the order of matrix multiplication is important. For example:

In [8]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print('A:')
print(A)
print('B:')
print(B)
print('A x B:')
print(A @ B)
print('B x A:')
print(B @ A)

A:
[[1 2]
 [3 4]]
B:
[[5 6]
 [7 8]]
A x B:
[[19 22]
 [43 50]]
B x A:
[[23 34]
 [31 46]]


In the case of addition of numbers, if we add 0 to any number, we get back the same number. In the case of matrix addition, if we add the zero matrix to any matrix, we get back the same matrix. For example:

In [9]:
A = np.array([[1, 2], [3, 4]])
zero = np.array([[0, 0], [0, 0]])
print('A:')
print(A)
print('A + zero:')
print(A + zero)
print('zero + A:')
print(zero + A)

A:
[[1 2]
 [3 4]]
A + zero:
[[1 2]
 [3 4]]
zero + A:
[[1 2]
 [3 4]]


In the case of multiplication of numbers, if we multiply any number by 1, we get back the same number. In the case of matrix multpilication, if we multiply any matrix by the identity matrix, we get back the same matrix. For example: 

In [10]:
A = np.array([[1, 2], [3, 4]])
identity = np.eye(2)
print('A:')
print(A)
print('A * identity:')
print(A @ identity )
print('identity * A:')
print(identity @ A)

A:
[[1 2]
 [3 4]]
A * identity:
[[1. 2.]
 [3. 4.]]
identity * A:
[[1. 2.]
 [3. 4.]]


In the case of multiplication of real numbers, each real number x except for 0 has a *multiplicative inverse* 1/x such that when x is multiplied by its multiplicative inverse, the result is 1.

In the case of matrices, some matrices have a multiplicative inverse and some do not. For example:

In [11]:
import numpy.linalg as la

A = np.array([[1, 2], [3, 4]])
A_inv = la.inv(A)

print('A:')
print(A)

print('multiplication of A by A_inv on the left or right results in the identity matrix:')
print(np.allclose(A_inv @ A, np.eye(2)))
print(np.allclose(A @ A_inv, np.eye(2)))

# the zero matrix does not have an inverse
zero = np.array([[0, 0], [0, 0]])
try:
    zero_inv = la.inv(zero)
except:
    print('\nthe zero matrix has no inverse!')

A:
[[1 2]
 [3 4]]
multiplication of A by A_inv on the left or right results in the identity matrix:
True
True

the zero matrix has no inverse!


Note that in the above example, we had to use the `allclose` function since we cannot use simple equality when using floating point numbers.

We can obtain the *transpose* of a matrix by exchaning rows and columns. For example:

In [12]:
A = np.array([[1, 2], [3, 4]])
print('A:')
print(A)
print('A Transpose:')
print(A.T)

A:
[[1 2]
 [3 4]]
A Transpose:
[[1 3]
 [2 4]]


It is convenient to have a test that we can apply to a matrix to see whether or not a given matrix has an inverse. It turns out that a matrix having a non-zero determinant is equivalent to that matrix being invertible. Conversely, if the determinant of a matrix is the zero matrix, then that matrix is not invertibe. For example:

In [13]:
A = np.array([[1, 2], [3, 4]])
A_inv = la.inv(A)
A_det = la.det(A)

print('A:')
print(A)
print('Determinant of A:')
print(A_det)
print('A has an inverse because its determinant is non-zero.')

# the zero matrix does not have an inverse
zero = np.array([[0, 0], [0, 0]])
zero_det = la.det(zero)
print('Determinant of zero matrix:')
print(zero_det)
print('the zero matrix has no inverse because its determinant is zero.')

A:
[[1 2]
 [3 4]]
Determinant of A:
-2.0000000000000004
A has an inverse because its determinant is non-zero.
Determinant of zero matrix:
0.0
the zero matrix has no inverse because its determinant is zero.


A vector is simply a matrix where one of the indices is always 1. If the first component is always 1, we call such a vector a *row vector*. If second component is always 1, we call such a vector a *column vector*.

The distinction between row vectors and column vectors is important in the context of vector operations such as the inner product, where we think of a row vector as a function that takes a column vector as input and returns a scalar as output.

For example:

In [14]:
row_vector = np.array([[1, 2, 3]])    
column_vector = np.array([[1, 2, 3]]).T 

print('row vetor:')
print(row_vector)
print('shape of row vector:')
print(row_vector.shape)
print('column vector:')
print(column_vector)
print('shape of column vector:')
print(column_vector.shape)

row vetor:
[[1 2 3]]
shape of row vector:
(1, 3)
column vector:
[[1]
 [2]
 [3]]
shape of column vector:
(3, 1)


If a vector has a shape (1, 3), then it has 1 row and 3 columns. If a vector has a shape (3, 1), then it has 3 rows and 1 column.

Two vectors are equal if all of their components are equal. For example:

In [15]:
v1 = np.array([[2, 4, 6]]).T 
v2 = np.array([[1+1, 2+2, 3+3]]).T

print('v1 and v2 are equal:')
print(np.array_equal(v1, v2))

v1 and v2 are equal:
True


Two vectors are added component-wise:

In [16]:
v1 = np.array([[1, 2, 3]]) 
v2 = np.array([[4, 5, 6]]) 

v1 + v2

array([[5, 7, 9]])

We can multiply a vector by a scalar as follows:

In [17]:
v = np.array([[1, 2, 3]]) 
scalar = 5

5 * v

array([[ 5, 10, 15]])

When added to another vector, the zero vector leaves the initial vector unchanged:

In [18]:
v = np.array([[1, 2, 3]]) 
zero_vector = np.array([[0, 0, 0]]) 

v + zero_vector
zero_vector + v

array([[1, 2, 3]])

We obtain a *linear combination* of vectors by combining vector addition with scalar multiplication. For example, the followwing is a linear combination of two vectors:

In [19]:
v1 = np.array([[1, 2, 3]]) 
v2 = np.array([[4, 5, 6]]) 

(2 * v1) + (3 * v2)

array([[14, 19, 24]])

The notion of a linear combination is useful, since it allows us to decompose a vector into simpler components.

In the context of quantum computing, we will need vectors whose entries are complex numbers. The following is an example of such a vector:

In [20]:
v = np.array([[
               6 - 4j,
               7 + 3j,
               4.2 - 8.1j,
               -3j
]]).T
v

array([[ 6. -4.j ],
       [ 7. +3.j ],
       [ 4.2-8.1j],
       [-0. -3.j ]])

Notice that in Python, we use the symbol `j` instead of `i` to denote the imaginary part of a complex number.

Given a complex vector, the *conjugate* operation switches the sign on the imaginary component of each complex number in the vector. For example: 

In [21]:
v = np.array([[
               6 - 4j,
               7 + 3j,
               4.2 - 8.1j,
               -3j
]]).T

np.conj(v)

array([[ 6. +4.j ],
       [ 7. -3.j ],
       [ 4.2+8.1j],
       [-0. +3.j ]])

Given a column vector, obtain its *dual vector* by applying the transpose and conjugation operation to the column vector. The operation which yields the dual vector is called the *dagger operation* or the *adjoint operation*. For example:

In [22]:
v = np.array([[
               6 - 4j,
               7 + 3j,
               4.2 - 8.1j,
               -3j
]]).T

print('v:')
print(v)
print('\ndual vector of v:')
print(np.conj(v).T)

v:
[[ 6. -4.j ]
 [ 7. +3.j ]
 [ 4.2-8.1j]
 [-0. -3.j ]]

dual vector of v:
[[ 6. +4.j   7. -3.j   4.2+8.1j -0. +3.j ]]


In the case of quantum computing, we represent the state of a quantum system as a linear combination, where the weights in the linear combination are complex numbers. In the context of quantum computing, we call a linear combination a *superposition*.

For example:

In [23]:
v1 = np.array([[1, 0]]).T
v2 = np.array([[0, 1]]).T

superposition = np.sqrt(1/3) * v1 + np.sqrt(2/3) * v2
print('superposition:')
print(superposition)

superposition:
[[0.57735027]
 [0.81649658]]


Quantum computing imposes a strict constraint on the weights involved in such superpositions: the sum of absolute values squared of the weights must equal exactly 1. The reason for this constraint is that the absolute value squared of a given weight represents the probability of measuring the state associated with that weight.

For example:

In [24]:
print('probability of measuring state v1:')
prob_v1 = np.abs(np.sqrt(1/3)) * np.abs(np.sqrt(1/3)) 
print(prob_v1)

prob_v2 = np.abs(np.sqrt(2/3)) * np.abs(np.sqrt(2/3))
print('probability of measuring state v2:')
print(prob_v2)

print('probability of measuring either state v1 or state v2:')
print(prob_v1 + prob_v2)

probability of measuring state v1:
0.3333333333333333
probability of measuring state v2:
0.6666666666666666
probability of measuring either state v1 or state v2:
1.0


Given vectors v1 and v2, we can compute the *inner product* of the two vectors by applying the dagger operation to v1 and matrix multiplying v1 and v2. For example:

In [25]:
v1 = np.array([[1+2j, 2-2j]]).T
v2 = np.array([[-1j, 0.5]]).T

new_v1 = np.conj(v1).T

inner_prod = new_v1 @ v2

print('v1:')
print(v1)
print('v2:')
print(v2)
print('inner product:')
print(inner_prod[0][0])

v1:
[[1.+2.j]
 [2.-2.j]]
v2:
[[-0. -1.j]
 [ 0.5+0.j]]
inner product:
(-1+0j)


The inner product gives us a way to measure the following: 

1. The *angle* between two vectors.
2. The *norm* of a vector (a generalization of the notion of length)
3. The distance between two vectors. 

If the inner product between two vectors is 0, then we say the two vectors are *orthogonal* (a generalization of the notion of a right angle). For example:

In [26]:
v1 = np.array([[1+1j, 2-2j]]).T
v2 = np.array([[-1j, 0.5]]).T

inner_prod = np.vdot(v1, v2)

print('v1:')
print(v1)
print('v2:')
print(v2)
print('inner product:')
print(inner_prod)

v1:
[[1.+1.j]
 [2.-2.j]]
v2:
[[-0. -1.j]
 [ 0.5+0.j]]
inner product:
0j


The standard basis vectors are a set of vectors which have a 1 in one entry and zeros everywhere else. It is important to note that the standard basis vectors are orthogonal to each other, regardless of how many dimensions are involved:

In [27]:
v1 = np.array([[1, 0, 0]])
v2 = np.array([[0, 1, 0]])
v3 = np.array([[0, 0, 1]])

inner_prod_1 = np.vdot(v1.T, v2)
inner_prod_2 = np.vdot(v1.T, v3)
inner_prod_3 = np.vdot(v2.T, v3)

print('inner product of v1 with v2:')
print(inner_prod_1)
print('inner product of v1 with v3:')
print(inner_prod_2)
print('inner product of v2 with v3:')
print(inner_prod_3)

inner product of v1 with v2:
0
inner product of v1 with v3:
0
inner product of v2 with v3:
0


We say that the standard basis vectors *span* a given vector space because any vector in that space can be expressed as a linear combination of the basis vectors. For example:

In [28]:
v1 = np.array([[1, 0, 0]])
v2 = np.array([[0, 1, 0]])
v3 = np.array([[0, 0, 1]])

v4 = np.array([[2, 3, 4]])
print ('v4:')
print (v4)

v5 = 2*v1 + 3*v2 + 4*v3
print('v5:')
print(v5)

v4:
[[2 3 4]]
v5:
[[2 3 4]]


We can use the inner product to compute the norm of a vector by taking the inner product of the vector with itself and then taking the square root of the result. For example:

In [29]:
v = np.array([[1, 1]]).T
print('v:')
print(v)

v_norm = np.sqrt(np.vdot(v, v))
print('norm of v:')
print(v_norm)

v:
[[1]
 [1]]
norm of v:
1.4142135623730951


If the norm of a vector is exactly 1, we call such a vector a *unit vector*. For example:

In [30]:
u = np.array([[1, 0]]).T
print('u:')
print(u)

u_norm = np.sqrt(np.vdot(u, u))
print('norm of u:')
print(u_norm)

u:
[[1]
 [0]]
norm of u:
1.0


Given a vector that is not a unit vector, we can *normalize* that vector by computing its norm and then scalar multiplying the initial vector by one over its norm. For example:

In [31]:
v = np.array([[1, 1]]).T
print('v:')
print(v)

v_norm = np.sqrt(np.vdot(v, v))
print('norm of v:')
print(v_norm)

normalized_v = (1/v_norm) * v
normalized_v_norm = np.sqrt(np.vdot(normalized_v, normalized_v))

print('normalized v:')
print(normalized_v)

print('norm of new vector:')
print(np.round(normalized_v_norm))

v:
[[1]
 [1]]
norm of v:
1.4142135623730951
normalized v:
[[0.70710678]
 [0.70710678]]
norm of new vector:
1.0


Recall that the standard basis vectors have a 1 in one component and zeros everywhere else. The standard basis vectors an example of an *orthonormal basis*, since each vector in the basis is normalized, and all of the vectors in the basis are orthogonal to each other. 

If we have a set of basis vectors which are not orthonormal, we can feed them into the Gram-Schmidt algorithm to obtain an orthonormal set of basis vectors as output. 

The classical Gram-Schmidt algorithm takes each vector and makes it orthogonal to all previous vectors. However, this algorithm turns out to not be numerically stable. If numerical precision is required, the modified Gram-Schmidt algorithm can be used instead. The modified Gram-Schmidt algorithm takes each vector and modifies it such that all forthcoming vectors are be orthogonal to it.

An example of the classical Gram-Schmidt algorithm is as follows:

In [32]:
def gram_schmidt(A):
    """
       Orthogonalize a set of vectors stored as the columns of matrix A.
       
       Based on https://gist.github.com/iizukak/1287876?permalink_comment_id=2935521#gistcomment-2935521
    """
    # number of vectors in the input matrix equals its number of columns
    n = A.shape[1]
    for j in range(n):
        # To orthogonalize the vector in column j with respect to the
        # previous vectors, subtract from it its projection onto
        # each of the previous vectors.
        for k in range(j):
            A[:, j] -= np.vdot(A[:, k], A[:, j]) * A[:, k]
        A[:, j] = A[:, j] / np.linalg.norm(A[:, j])
    return A

# initial basis vectors
v1 = np.array([1j, 1j, 1j]).reshape((3,1))
v2 = np.array([0, 1j, 1j]).reshape((3,1))
v3 = np.array([0, 0, 1j]).reshape((3,1))

# feed initial basis vectors into Gram-Schmidt Algorithm
X = np.hstack([v1,v2,v3])

# orthonormal basis vectors
Y = np.round(gram_schmidt(X),3)

print ('input vectors:')
print(v1)
print(v2)
print(v3)

b1 = Y[:, 0].reshape(3,1)
b2 = Y[:, 1].reshape(3,1)
b3 = Y[:, 2].reshape(3,1)

print('output vectors:')
print(b1)
print(b2)
print(b3)

print('output vector norms:')
print(np.round(la.norm(b1)))
print(np.round(la.norm(b2)))
print(np.round(la.norm(b3)))

print('output vector inner products:')
inner_prod_1 = np.vdot(b1.T, b2)
inner_prod_2 = np.vdot(b1.T, b3)
inner_prod_3 = np.vdot(b2.T, b3)
print(inner_prod_1)
print(inner_prod_2)
print(inner_prod_3)

input vectors:
[[0.+1.j]
 [0.+1.j]
 [0.+1.j]]
[[0.+0.j]
 [0.+1.j]
 [0.+1.j]]
[[0.+0.j]
 [0.+0.j]
 [0.+1.j]]
output vectors:
[[0.+0.577j]
 [0.+0.577j]
 [0.+0.577j]]
[[0.-0.816j]
 [0.+0.408j]
 [0.+0.408j]]
[[0.-0.j   ]
 [0.-0.707j]
 [0.+0.707j]]
output vector norms:
1.0
1.0
1.0
output vector inner products:
0j
0j
0j


Given two vectors, we can compute the distance between the two vectors by subtracting one from the other to obtain a third vector and then measuring the norm of the third vector. For example:

In [33]:
v1 = np.array([[1j, 0]]).T
v2 = np.array([[0, 1j]]).T

la.norm(v1 - v2)

1.4142135623730951

We have seen that the inner product takes two vectors as input and returns one vector as output. In contrast, the *outer product* takes two vectors as input and returns a matrix as output. 

In particular, whereas the inner product multiplies a row vector by a column vector, the outer product multiplies a column vector by a row vector. 

Given two column vectors v1 and v2, the outer product is obtained by multiplying each element of v1 by each element of the dual vector of v2.

For example:

In [34]:
v1 = np.array([[1, 2, 3]]).T
v2 = np.array([[4, 5]]).T

print('outer product:')
np.outer(v1, v2)

outer product:


array([[ 4,  5],
       [ 8, 10],
       [12, 15]])

The *kronecker product* is closely related to the outer product in the sense that the kronecker product flattens the outer product into a single vector. For example:

In [35]:
v1 = np.array([[1, 2, 3]]).T
v2 = np.array([[4, 5]]).T

print('outer product:')
print(np.outer(v1, v2))

print('kronecker product:')
np.kron(v1, v2)

outer product:
[[ 4  5]
 [ 8 10]
 [12 15]]
kronecker product:


array([[ 4],
       [ 5],
       [ 8],
       [10],
       [12],
       [15]])

We can also apply the kronecker product to pairs of matrices. The kronecker product is also called the *tensor product*. For example:

In [36]:
A = np.array([
               [3+2j, 5-1j, 2j],
               [0, 12, 6-3j],
               [2, 4+4j, 9+3j]
              ]
)

B = np.array([
               [1, 3+4j, 5-7j],
               [10+2j, 6, 2+5j],
               [0, 1, 2+9j]
              ]
)

np.kron(A, B)

array([[  3.  +2.j,   1. +18.j,  29. -11.j,   5.  -1.j,  19. +17.j,
         18. -40.j,   0.  +2.j,  -8.  +6.j,  14. +10.j],
       [ 26. +26.j,  18. +12.j,  -4. +19.j,  52.  +0.j,  30.  -6.j,
         15. +23.j,  -4. +20.j,   0. +12.j, -10.  +4.j],
       [  0.  +0.j,   3.  +2.j, -12. +31.j,   0.  +0.j,   5.  -1.j,
         19. +43.j,   0.  +0.j,   0.  +2.j, -18.  +4.j],
       [  0.  +0.j,   0.  +0.j,   0.  +0.j,  12.  +0.j,  36. +48.j,
         60. -84.j,   6.  -3.j,  30. +15.j,   9. -57.j],
       [  0.  +0.j,   0.  +0.j,   0.  +0.j, 120. +24.j,  72.  +0.j,
         24. +60.j,  66. -18.j,  36. -18.j,  27. +24.j],
       [  0.  +0.j,   0.  +0.j,   0.  +0.j,   0.  +0.j,  12.  +0.j,
         24.+108.j,   0.  +0.j,   6.  -3.j,  39. +48.j],
       [  2.  +0.j,   6.  +8.j,  10. -14.j,   4.  +4.j,  -4. +28.j,
         48.  -8.j,   9.  +3.j,  15. +45.j,  66. -48.j],
       [ 20.  +4.j,  12.  +0.j,   4. +10.j,  32. +48.j,  24. +24.j,
        -12. +28.j,  84. +48.j,  54. +18.j,   3. +51.j],


In the context of quantum mechanics, the outer product is related to the notion of a *projection operator*. In particular, if we take the outer product of a basis vector with itself, we obtain a projection operator. The *completeness relation* says that the sum of all projection operators always yields the identity matrix. 

For example:

In [37]:
v1 = np.array([[0, 1]]).T
v2 = np.array([[1, 0]]).T

v1_outer_v1 = np.outer(v1, v1)
v2_outer_v2 = np.outer(v2, v2)

print('v1:')
print(v1)
print('v2:')
print(v2)

print('outer product of v1 with v1:')
print(v1_outer_v1)
print('outer product of v2 with v2:')
print(v2_outer_v2)

print('sum of outer products:')
print(v1_outer_v1 + v2_outer_v2)

v1:
[[0]
 [1]]
v2:
[[1]
 [0]]
outer product of v1 with v1:
[[0 0]
 [0 1]]
outer product of v2 with v2:
[[1 0]
 [0 0]]
sum of outer products:
[[1 0]
 [0 1]]


The reason that the outer product of a basis vector is called a *projection operator* is that such matrices have the effect of projecting out just one component of a given vector. For example:

In [38]:
v1 = np.array([[1, 0, 0]]).T
v2 = np.array([[0, 1, 0]]).T
v3 = np.array([[0, 0, 1]]).T

v1_outer_v1 = np.outer(v1, v1)
v2_outer_v2 = np.outer(v2, v2)
v3_outer_v3 = np.outer(v3, v3)


print('v1:')
print(v1)
print('v2:')
print(v2)
print('v3:')
print(v3)

print('outer product of v1 with v1:')
print(v1_outer_v1)
print('outer product of v2 with v2:')
print(v2_outer_v2)

print('outer product of v3 with v3:')
print(v3_outer_v3)

print('sum of outer products:')
print(v1_outer_v1 + v2_outer_v2 + v3_outer_v3)

v =  np.array([[1+2j, 3+4j, 5+6j]]).T

print('v:')
print(v)

print ('action of outer products on v:')
print(v1_outer_v1 @ v)
print(v2_outer_v2 @ v)
print(v3_outer_v3 @ v)

v1:
[[1]
 [0]
 [0]]
v2:
[[0]
 [1]
 [0]]
v3:
[[0]
 [0]
 [1]]
outer product of v1 with v1:
[[1 0 0]
 [0 0 0]
 [0 0 0]]
outer product of v2 with v2:
[[0 0 0]
 [0 1 0]
 [0 0 0]]
outer product of v3 with v3:
[[0 0 0]
 [0 0 0]
 [0 0 1]]
sum of outer products:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
v:
[[1.+2.j]
 [3.+4.j]
 [5.+6.j]]
action of outer products on v:
[[1.+2.j]
 [0.+0.j]
 [0.+0.j]]
[[0.+0.j]
 [3.+4.j]
 [0.+0.j]]
[[0.+0.j]
 [0.+0.j]
 [5.+6.j]]


from the above, we can see that the ith projection operator returns a vector containing only the ith component of the input vector, and all other components of the output vector are 0.

An n-by-n matrix $A$ is called *hermitian* if it is equal to $A^{T*}$, where $^*$ deontes the result of complex conjugating each entry in A. This operation is often denoted $A^\dagger$ and pronounced "dagger". For example:

In [39]:
A = np.array([
              [5, 4+5j, 6-16j],
              [4 - 5j, 13, 7],
              [6 + 16j, 7, -2.1]])

A_dagger = np.conj(A.T)

print('A:')
print(A)
print('A dagger:')
print(A_dagger)
print('A is hermitian:', np.array_equal(A, A_dagger))

A:
[[ 5.  +0.j  4.  +5.j  6. -16.j]
 [ 4.  -5.j 13.  +0.j  7.  +0.j]
 [ 6. +16.j  7.  +0.j -2.1 +0.j]]
A dagger:
[[ 5.  -0.j  4.  +5.j  6. -16.j]
 [ 4.  -5.j 13.  -0.j  7.  -0.j]
 [ 6. +16.j  7.  -0.j -2.1 -0.j]]
A is hermitian: True


A unitary matrix is a type of invertible matrix. A unitary matrix is invertible *and* its inverse
is its own adjoint. That is, a matrix A is unitary if $A * A^\dagger = I_n$ 

For example:

In [40]:
A = np.array([
    [1/np.sqrt(2), 1/np.sqrt(2)],
    [1/np.sqrt(2)*1j, -1/np.sqrt(2)*1j]
])

print('A:')
print(np.round(A))
print('A dagger:')
print(np.round(A.conj().T))
print('A times A dagger:')
print(np.round(A @ A.conj().T))

A:
[[ 1.+0.j  1.+0.j]
 [ 0.+1.j -0.-1.j]]
A dagger:
[[ 1.-0.j  0.-1.j]
 [ 1.-0.j -0.+1.j]]
A times A dagger:
[[1.+0.j 0.+0.j]
 [0.-0.j 1.+0.j]]


A unitary matrix preserves the norm. This is a consequence of the fact that a unitary matrix preserves the inner product, and the norm is defined using the inner product. From the persepcteive of quantum mechanics, a unitary matrix preserves probability and implies reversible transformations.

The following example demonstrates how a unitary matrix preserves the inner product:

In [41]:
v1 = np.array([[1, 2]]).T
v2 = np.array([[3, 4]]).T

U = np.array([
    [1/np.sqrt(2), 1/np.sqrt(2)],
    [1/np.sqrt(2)*1j, -1/np.sqrt(2)*1j]
])

print('v1:')
print(v1)
print('v2:')
print(v2)
print('U:')
print(U)
print('inner product without U:')
print(np.vdot(v1, v2))
print('inner product with U:')
print(np.round(np.vdot(U@v1, U@v2)))

v1:
[[1]
 [2]]
v2:
[[3]
 [4]]
U:
[[ 0.70710678+0.j          0.70710678+0.j        ]
 [ 0.        +0.70710678j -0.        -0.70710678j]]
inner product without U:
11
inner product with U:
(11+0j)


The following example demonstrates that a unitary matrix preserves the norm:

In [42]:
v = np.array([[1, 2]]).T

U = np.array([
    [1/np.sqrt(2), 1/np.sqrt(2)],
    [1/np.sqrt(2)*1j, -1/np.sqrt(2)*1j]
])

print('v:')
print(v)

print('norm of v:')
print(np.round(la.norm(v)))
print('norm of v after multiplication by U:')
print(np.round(la.norm((U @ v))))

v:
[[1]
 [2]]
norm of v:
2.0
norm of v after multiplication by U:
2.0


A unitary matrix also preserves distances between vectors. For example:

In [43]:
v1 = np.array([[1, 2]]).T
v2 = np.array([[3, 4]]).T

U = np.array([
    [1/np.sqrt(2), 1/np.sqrt(2)],
    [1/np.sqrt(2)*1j, -1/np.sqrt(2)*1j]
])

print('v1:')
print(v1)
print('v2:')
print(v2)
print('U:')
print(U)
print('distance without U:')
print(np.round(la.norm(v1 - v2), 5))
print('distance with U:')
print(np.round(la.norm(U@v1 - U@v2), 5))

v1:
[[1]
 [2]]
v2:
[[3]
 [4]]
U:
[[ 0.70710678+0.j          0.70710678+0.j        ]
 [ 0.        +0.70710678j -0.        -0.70710678j]]
distance without U:
2.82843
distance with U:
2.82843


## Quantum Theory

Quantum theory is concerned with the probability of making various measurements. However, becuase it uses complex amplitudes rather than standard probabilities, quantum theory allows for a phenomenon known as *interference*. 

If p1 and p2 are two real numbers between 0 and 1, then (p1 + p2) ≥ p1 and (p1 + p2) ≥ p2.

However, if $c_1$ and $c_2$ are two complex numbers with associated squares of modulus $|c_1|^2$ and $|c_2|^2$, then $|c_1 + c_2|^2$ need not be bigger than $|c_1|^2$ and it also need not be bigger than $|c_2|^2$.

For example:

In [44]:
c1 = 5 + 3j  
c2 = -3 - 2j

print('modulus of c1 squared:')
print(np.round((np.abs(c1) * np.abs(c1))))
print('modulus of c2 squared:')
print(np.round(np.abs(c2) * np.abs(c2)))

print('modulus of sum squared:')
print(np.round(np.abs(c1 + c2) * np.abs(c1 + c2)))

modulus of c1 squared:
34.0
modulus of c2 squared:
13.0
modulus of sum squared:
5.0


As preparation for using matrices to manipulate qbits, we can first encode classical bits as matrices indexed by binary numbers.

For example, suppose we have a register consisting of two classical bits. These two bits can be in the following states:

00
01
10
11

If we adopt the convention of indexing our vectors with binary numbers, then we can represent these four states with basis vectors as follows:

00 -> [1, 0, 0, 0]

01 -> [0, 1, 0, 0]

10 -> [0, 0, 1, 0]

11 -> [0, 0, 0, 1]

The above encoding works by reading the current state of our bits as a binary number, and then writing a one in the position whose index (in binary) corresponds to that binary number. 

Notice that to represent the current state of two bits using this encoding, we require $2^2$ bits. In general, to represen the state of n bits using this encoding, we require $2^n$ bits.

If we use [1 0] to represent the fact that a given bit is a 0, and we use [1, 0] to represent the fact that a given bit is zero, then we can use the kronecker product to compute the current overall state of our bits:

In [45]:
zero = np.array([[1, 0]]).T
one = np.array([[0, 1]]).T

print('00 = 0:')
print(np.kron(zero, zero))
print('01 = 1:')
print(np.kron(zero, one))
print('10 = 2:')
print(np.kron(one, zero))
print('11 = 3:')
print(np.kron(one, one))

00 = 0:
[[1]
 [0]
 [0]
 [0]]
01 = 1:
[[0]
 [1]
 [0]
 [0]]
10 = 2:
[[0]
 [0]
 [1]
 [0]]
11 = 3:
[[0]
 [0]
 [0]
 [1]]


Just as we can encode bits as vectors, we can encode logic gates as matrices that operate on those vectors. 

The simpliest logic gate to implement is the NOT gate:

In [46]:
NOT = np.array([
                [0, 1], 
                [1, 0]
])

print('zero:')
print(zero)

print('one:')
print(one)

print('NOT of zero:')
print(NOT @ zero)

print('one:')
print(one)
print('NOT of one:')
print(NOT @ one)

zero:
[[1]
 [0]]
one:
[[0]
 [1]]
NOT of zero:
[[0]
 [1]]
one:
[[0]
 [1]]
NOT of one:
[[1]
 [0]]


Because AND takes to bits as input and returns one output, we need a 2 x 4 matrix to represent it. Only an input corresponding to 11 shoud return an output of 1:

In [47]:
AND = np.array([[1, 1, 1, 0],
                [0, 0, 0, 1]
               ])

zero_zero = np.kron(zero, zero)
zero_one = np.kron(zero, one)
one_zero = np.kron(one, zero)
one_one = np.kron(one, one)

print('zero:')
print(zero)

print('one:')
print(one)

print('AND(00):')
print(AND @ zero_zero)
print('AND(01):')
print(AND @ zero_one)
print('AND(10):')
print(AND @ one_zero)
print('AND(11):')
print(AND @ one_one)

zero:
[[1]
 [0]]
one:
[[0]
 [1]]
AND(00):
[[1]
 [0]]
AND(01):
[[1]
 [0]]
AND(10):
[[1]
 [0]]
AND(11):
[[0]
 [1]]


The OR gate can be implemented as follows:

In [48]:
OR = np.array([[1, 0, 0, 0],
               [0, 1, 1, 1]
])

print('zero:')
print(zero)

print('one:')
print(one)

print('OR(00):')
print(OR @ zero_zero)
print('OR(01):')
print(OR @ zero_one)
print('OR(10):')
print(OR @ one_zero)
print('OR(11):')
print(OR @ one_one)

zero:
[[1]
 [0]]
one:
[[0]
 [1]]
OR(00):
[[1]
 [0]]
OR(01):
[[0]
 [1]]
OR(10):
[[0]
 [1]]
OR(11):
[[0]
 [1]]


We can implement more complex gates such as NAND using matrix multiplication:

In [49]:
NAND = NOT @ AND

print('zero:')
print(zero)

print('one:')
print(one)

print('NAND(00):')
print(NAND @ zero_zero)
print('NAND(01):')
print(NAND @ zero_one)
print('OR(10):')
print(NAND @ one_zero)
print('NAND(11):')
print(NAND @ one_one)

zero:
[[1]
 [0]]
one:
[[0]
 [1]]
NAND(00):
[[0]
 [1]]
NAND(01):
[[0]
 [1]]
OR(10):
[[0]
 [1]]
NAND(11):
[[1]
 [0]]


We have seen that in the case of classical computing, if we have n bits we can represent the state of our bits with a vector of length $2^n$, where one entry is 1, and the remaining entries are 0. 

In the case of quantum computing, if we have n qbits we can represent the state of our qbits with a vector of length $2^n$, where each entry is a complex number, and the sum of the moduli squared of all of the complex numbers in the vector sum to 1.

Because transformations on qbits must be represented by unitary operators, we cannot use classical operators such as AND, since they are not unitary.

The NOT and IDENTITY gates are reversible, and there are others.

The controlled-NOT gate takes two qbits as input and returns one qbit as output. The first input qbit is known as the *control qubit* and the second is known as the *target qubit*. If the control qubit is |1〉then the controlled-NOT gate flips the target qubit's state. Otherwose, the target qbit is left unchanged.

The controlled-NOT gate works as follows:

In [50]:
CNOT = np.array([
          [1, 0, 0, 0],
          [0, 1, 0, 0],
          [0, 0, 0, 1],
          [0, 0, 1, 0]
])

zero_zero = np.kron(zero, zero)
zero_one = np.kron(zero, one)
one_zero = np.kron(one, zero)
one_one = np.kron(one, one)

print('zero:')
print(zero)

print('one:')
print(one)

# target qbit remains unchanged
print('CNOT(00):')
print(CNOT @ zero_zero)

# target qbit remains unchanged
print('CNOT(01):')
print(CNOT @ zero_one)

# target qbit is flipped
print('CNOT(10):')
print(CNOT @ one_zero)

# target qbit is flipped
print('CNOT(11):')
print(CNOT @ one_one)

zero:
[[1]
 [0]]
one:
[[0]
 [1]]
CNOT(00):
[[1]
 [0]
 [0]
 [0]]
CNOT(01):
[[0]
 [1]
 [0]
 [0]]
CNOT(10):
[[0]
 [0]
 [0]
 [1]]
CNOT(11):
[[0]
 [0]
 [1]
 [0]]


The CNOT gate is its own inverse:

In [51]:
CNOT = np.array([
          [1, 0, 0, 0],
          [0, 1, 0, 0],
          [0, 0, 0, 1],
          [0, 0, 1, 0]
])

print('CNOT times CNOT:')
print(CNOT @ CNOT)

CNOT times CNOT:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


## Interpretation of Quantum Gates

We can get a better understanding of how to interpret quantum gates by visualizing how a given quantum gate changes the probabilities of making various measurements.

For example, if we have two qbits, the Hadamard gate puts the qbits into a superposition, such that we have a 50% probability of measuring either the |0> state or the |1> state:

In [52]:
H = 1/np.sqrt(2.0) * np.array([[1,1],[1,-1]])

zero = np.array([[1, 0]]).T
one = np.array([[0, 1]]).T

print('zero state after applying Hadamard gate:')
print(H @ zero)

print('one state after applying Hadamard gate:')
print(H @ one)

zero state after applying Hadamard gate:
[[0.70710678]
 [0.70710678]]
one state after applying Hadamard gate:
[[ 0.70710678]
 [-0.70710678]]


We can simulate a quantum measurement by computing the modulus squared of a weight and then comparing that value to a number selected from a uniform distribution between 0 and 1. Notice that in the case of the Hadamard basis, we measure zero about half the time, and one about half the time:

In [53]:
def measure_in_computational_basis(state):
    pr_zero = np.absolute(state[0])**2
    U = np.random.uniform()
    if pr_zero > U:
        return 0
    else:
        return 1
    
H = 1/np.sqrt(2.0) * np.array([[1,1],[1,-1]])

for _ in range(10):
    print(measure_in_computational_basis(H @ zero))

0
0
1
1
1
1
0
0
1
0


The Pauli Y Gate has the following effects:

In [54]:
Y = np.array([
                [0, -1j], 
                [1j, 0]
])

print('zero:')
print(zero)

print('one:')
print(one)

print('zero state after applying Y gate:')
print(Y @ zero)

print('one state after applying Y gate:')
print(Y @ one)

zero:
[[1]
 [0]]
one:
[[0]
 [1]]
zero state after applying Y gate:
[[0.+0.j]
 [0.+1.j]]
one state after applying Y gate:
[[0.-1.j]
 [0.+0.j]]


The Pauli Z gate has the following effects:

In [55]:
Z = np.array([
                [1, 0], 
                [0, -1]
])

print('zero:')
print(zero)

print('one:')
print(one)

print('zero state after applying Z gate:')
print(Z @ zero)

print('one state after applying Z gate:')
print(Z @ one)

zero:
[[1]
 [0]]
one:
[[0]
 [1]]
zero state after applying Z gate:
[[1]
 [0]]
one state after applying Z gate:
[[ 0]
 [-1]]


The Phase gate has the following effects:

In [56]:
PHASE = np.array([
                [1, 0], 
                [0, 1j]
])

print('zero:')
print(zero)

print('one:')
print(one)

print('zero state after applying PHASE gate:')
print(PHASE @ zero)

print('one state after applying PHASE gate:')
print(PHASE @ one)

zero:
[[1]
 [0]]
one:
[[0]
 [1]]
zero state after applying PHASE gate:
[[1.+0.j]
 [0.+0.j]]
one state after applying PHASE gate:
[[0.+0.j]
 [0.+1.j]]


The following implementation of Gover's algorithm gives a sense of how quantum algorithms work. Instead of searching directly for a bit string such as 101, we can instead boost the amplitude corresponding to index 5 in a qbit array: 

Based on https://quantumcomputing.stackexchange.com/q/5364

In [57]:
def dagger(m):
    return np.transpose(np.conjugate(m))

def proj(m):
    return m * dagger(m)

# identity matrix for 3 qubits = 8x8 matrix
identity = np.identity(2**3)

# hadamard matrix for 1, 2 and 3 qubits
H1 = (1 / np.sqrt(2)) * np.matrix([[1.0, 1.0], [1.0, -1.0]], dtype=np.complex256) 
H2 = np.kron(H1, H1)
H3 = np.kron(H2, H1)

# 3 qubit zero vector |000>
zero3 = np.array([[1],[0],[0],[0],[0],[0],[0],[0]], dtype=np.complex256)

# phase shift operator  2*|0><0| - I  for 3 qubits
PS3 = 2 * proj(zero3) - identity

# reflection around the mean
R = H3 * PS3 * H3

# 3 qbit oracle, marking/negating state |101> = column vector (0 0 0 0 0 1 0 0)
O = identity
O[5,5] = -1

# grover operator
G = R * O

# start state |000>
x0 = H3 * zero3

# apply grover step two times
x1 = G * x0

x2 = G * x1
print (np.round(x2, 3))

[[-0.088+0.j]
 [-0.088+0.j]
 [-0.088+0.j]
 [-0.088+0.j]
 [-0.088+0.j]
 [ 0.972+0.j]
 [-0.088+0.j]
 [-0.088+0.j]]
